name: cg-gnn
channels:
  - defaults
dependencies:
  - bokeh
  - dglteam::dgl-cuda11.6
  - h5py
  - matplotlib
  - networkx
  - numpy
  - nvidia::cudatoolkit=11.6
  - pandas
  - psycopg2
  - pyshp
  - pytables
  - python=3.9
  - pytorch::pytorch>=1.12
  - pytorch::pytorch-cuda=11.6
  - scikit-learn
  - scipy
  - tqdm