name: hactnet_hpc5
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - alembic=1.0.9=py37_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asn1crypto=1.4.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - brotli=1.0.9=h9c3ff4c_4
  - brotlipy=0.7.0=py37h5e8e339_1001
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py37h89c1867_1
  - cffi=1.14.6=py37h400218f_0
  - chardet=4.0.0=py37h89c1867_2
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.3=py37h89c1867_1
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - configparser=5.1.0=pyhd8ed1ab_0
  - cryptography=35.0.0=py37h5d9358c_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd8ed1ab_0
  - databricks-cli=0.12.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=he372182_0
  - docker-py=5.0.3=py37h89c1867_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h9c3ff4c_0
  - ffmpeg=4.3=hf484d3e_0
  - flask=2.0.2=pyhd8ed1ab_0
  - fontconfig=2.13.1=hba837de_1005
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.24=pyhd8ed1ab_0
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=h28cd5cc_2
  - gunicorn=20.1.0=py37h89c1867_1
  - icu=58.2=hf484d3e_1000
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.1=py37h89c1867_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - itsdangerous=2.0.1=pyhd8ed1ab_0
  - jinja2=3.0.2=pyhd8ed1ab_0
  - jpeg=9d=h7f8727e_0
  - kiwisolver=1.3.1=py37h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.15.8=h780b84a_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - mako=1.1.5=pyhd8ed1ab_0
  - markupsafe=2.0.1=py37h5e8e339_0
  - matplotlib=3.4.3=py37h89c1867_1
  - matplotlib-base=3.4.3=py37hbbc1b5f_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - mlflow=1.20.2=py37h02d9ccd_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=heee7806_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.3=pyhd3eb1b0_0
  - numpy=1.21.2=py37h20f2e39_0
  - numpy-base=1.21.2=py37h79a1101_0
  - olefile=0.46=py37_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.2.5=py37h219a48f_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.4.0=py37h5aabda8_0
  - pip=21.0.1=py37h06a4308_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.18.5=pyhd8ed1ab_0
  - protobuf=3.15.8=py37hcd2ae1e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.5=pyhd8ed1ab_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pysocks=1.7.1=py37h89c1867_4
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=py_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.10.0=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd8ed1ab_0
  - pyyaml=5.4.1=py37h5e8e339_0
  - qt=5.9.7=h5867ecd_1
  - querystring_parser=1.2.4=py_0
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd8ed1ab_0
  - scipy=1.7.1=py37h292c36d_2
  - setuptools=58.0.4=py37h06a4308_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlalchemy=1.3.23=py37h5e8e339_0
  - sqlite=3.36.0=hc218d9a_0
  - sqlparse=0.4.2=pyhd8ed1ab_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tenacity=8.0.1=pyhd8ed1ab_0
  - tk=8.6.11=h1ccaba5_0
  - torchvision=0.11.1=py37_cu113
  - tornado=6.1=py37h5e8e339_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - websocket-client=0.57.0=py37h89c1867_6
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - cached-property==1.5.2
    - dgl==0.4.3.post2
    - h5py==3.5.0
    - histocartography==0.2.0
    - imageio==2.10.3
    - joblib==1.1.0
    - opencv-python==4.5.4.58
    - pywavelets==1.1.1
    - scikit-image==0.18.3
    - scikit-learn==1.0.1
    - seaborn==0.11.2
    - sklearn==0.0
    - threadpoolctl==3.0.0
    - tifffile==2021.11.2
prefix: /nadeem_lab/miniconda3/envs/hactnet_hpc5
