name: hact
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alembic=1.8.1=pyhd8ed1ab_0
  - alsa-lib=1.2.6.1=h7f98852_0
  - aom=3.4.0=h27087fc_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asn1crypto=1.5.1=pyhd8ed1ab_0
  - astroid=2.11.7=py39h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - autopep8=1.6.0=pyhd3eb1b0_1
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - blosc=1.21.0=h4ff587b_1
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.07.19=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=ha61ee94_1013
  - certifi=2022.9.14=py39h06a4308_0
  - cffi=1.15.1=py39h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=py39hf3d152e_0
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - configparser=5.3.0=pyhd8ed1ab_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - curl=7.84.0=h5eee18b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py39h27cfd23_0
  - dask-core=2022.7.0=py39h06a4308_0
  - databricks-cli=0.17.3=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - dgl-cuda11.3=0.9.0=py39_0
  - dill=0.3.4=pyhd3eb1b0_0
  - docker-py=5.0.3=py39hf3d152e_2
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.4.2=gpl_hfe78399_107
  - fftw=3.3.9=h27cfd23_1
  - flask=2.2.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=hc2a2eb6_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=hca18f0e_0
  - fsspec=2022.7.1=py39h06a4308_0
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h7b6447c_0
  - git=2.34.1=pl5262hc120c5b_0
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - glib=2.72.1=h6239696_0
  - glib-tools=2.72.1=h6239696_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.7.7=hf3e180e_0
  - graphite2=1.3.13=h58526e2_1001
  - greenlet=1.1.1=py39h295c915_0
  - gst-plugins-base=1.20.3=hf6a322e_0
  - gstreamer=1.20.3=hd4edc92_1
  - gunicorn=20.1.0=py39hf3d152e_2
  - h5py=3.7.0=nompi_py39h63b1161_100
  - harfbuzz=4.4.1=hf9f4e7c_0
  - hdf5=1.12.1=nompi_h2386368_104
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd3eb1b0_0
  - imageio=2.19.3=py39h06a4308_0
  - importlib-metadata=4.11.4=py39hf3d152e_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - isort=5.9.3=pyhd3eb1b0_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jack=1.9.18=h8c3723f_1002
  - jasper=2.0.33=ha77e612_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - json-c=0.16=hc379101_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py39h295c915_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7b6447c_0
  - lazy-object-proxy=1.6.0=py39h27cfd23_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcap=2.64=ha37c62d_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=14.0.6=default_h2e3cab8_0
  - libclang13=14.0.6=default_h3a83d3e_0
  - libcups=2.3.3=h3e49a29_2
  - libcurl=7.84.0=h91b91d3_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.8=h7f8727e_5
  - libdrm=2.4.113=h166bdaf_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.72.1=h2d90d5f_0
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm14=14.0.6=he0ac6c6_0
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.6.0=py39hd011c1b_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=hbc83047_0
  - libpq=14.5=hd77ab85_0
  - libprotobuf=3.20.1=h6239696_4
  - libsndfile=1.0.31=h9c3ff4c_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.4.0=hecacb30_0
  - libtool=2.4.6=h9c3ff4c_1008
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libva=2.15.0=h166bdaf_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h22db469_4
  - libzlib=1.2.12=h166bdaf_3
  - llvm-openmp=14.0.4=he0ac6c6_0
  - locket=1.0.0=py39h06a4308_0
  - lz4-c=1.9.3=h295c915_1
  - lzo=2.10=h7b6447c_2
  - mako=1.2.2=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39hb9d737c_1
  - matplotlib=3.5.2=py39h06a4308_0
  - matplotlib-base=3.5.2=py39hf590b9c_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mlflow=1.28.0=py39ha39b057_0
  - mock=4.0.3=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - mypy=0.910=pyhd3eb1b0_0
  - mypy_extensions=0.4.3=py39h06a4308_1
  - mysql-common=8.0.30=haf5c9bc_1
  - mysql-libs=8.0.30=h28c427c_1
  - ncurses=6.3=h5eee18b_3
  - nettle=3.8.1=hc379101_1
  - networkx=2.8.4=py39h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.78=h2350873_0
  - numexpr=2.8.3=py39h807cd23_0
  - numpy=1.21.5=py39h6c91a56_3
  - numpy-base=1.21.5=py39ha15fc14_3
  - oauthlib=3.2.1=pyhd8ed1ab_0
  - opencv=4.6.0=py39hf3d152e_0
  - openh264=2.3.0=h27087fc_0
  - openssl=1.1.1q=h7f8727e_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py39h6a678d5_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=h295c915_0
  - pcre2=10.37=he7ceb23_1
  - perl=5.26.2=h14c3975_0
  - pillow=9.2.0=py39hace64e9_1
  - pip=22.1.2=py39h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=2.5.2=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - portaudio=19.6.0=h57a0ea0_5
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.20.3=pyhd8ed1ab_0
  - protobuf=3.20.1=py39h5a03fae_0
  - psutil=5.9.0=py39h5eee18b_0
  - psycopg2=2.9.3=py39h3811e60_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio=14.0=h583eb01_5
  - py-opencv=4.6.0=py39hef51801_0
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=pyhd8ed1ab_0
  - pylint=2.14.5=py39h06a4308_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.7=py39h18e9c17_0
  - pyqt5-sip=12.11.0=py39h5a03fae_0
  - pyshp=2.1.3=pyhd3eb1b0_0
  - pysocks=1.7.1=py39h06a4308_0
  - pytables=3.7.0=py39h9da3b7f_0
  - python=3.9.13=h9a8a25e_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py39h06a4308_0
  - pywavelets=1.3.0=py39h7f8727e_0
  - pyyaml=6.0=py39hb9d737c_4
  - qt-main=5.15.4=ha5833f6_2
  - querystring_parser=1.2.4=py_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py39h06a4308_0
  - scikit-image=0.16.2=py39ha9443f7_0
  - scikit-learn=1.1.1=py39h6a678d5_0
  - scipy=1.7.3=py39h6c91a56_2
  - setuptools=63.4.1=py39h06a4308_0
  - sip=6.6.2=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=3.0.5=pyh44b312d_0
  - sqlalchemy=1.4.13=py39h3811e60_0
  - sqlite=3.39.2=h5082296_0
  - sqlparse=0.4.2=pyhd8ed1ab_0
  - svt-av1=1.2.1=h27087fc_0
  - tabulate=0.8.10=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39h06a4308_0
  - tomlkit=0.11.1=py39h06a4308_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.12.1=py39_cu113
  - torchvision=0.13.1=py39_cu113
  - tornado=6.2=py39h5eee18b_0
  - tqdm=4.64.0=py39h06a4308_0
  - types-pyyaml=6.0.11=pyhd8ed1ab_0
  - typing-extensions=4.3.0=py39h06a4308_0
  - typing_extensions=4.3.0=py39h06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.11=py39h06a4308_0
  - websocket-client=1.4.1=pyhd8ed1ab_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py39h5eee18b_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7f98852_2
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.2=ha4553b6_0
